- smpplib/client.py
- smpplib/command.py
This adds support for alert_notification PDUs which openbsc SMPP generates each time a phone attaches to or detaches from the GSM network.
Without this patch an alert_notification PDU generates an assert inside the program using python-smpplib
[ This adds to very minor change to hopefully allow the PR. The original contributor did the work for me, and I know they are pretty busy. ]
> command.py: Add support for alert_notification PDU (replaces PR #20)

- smpplib/command.py
- smpplib/pdu.py
It's already done in all other integer types and was probably forgotten
here. It's not a big issue because this path is only called for sending
mandatory parameters, and all integer mandatory parameters I could find
are only 1 byte long. However, add it for completeness and to avoid any
future issues in case of refactor.
> command: Pack struct in big-endian byte order

- smpplib/client.py
_message_received():
In the case where one might want to return a status to SMSC based
on the outcome of handling of a deliver_sm, we need to be able to
return that status and use it in the creation of the deliver_sm_resp
> client.py: Allow and use a return value from message_received_handler()

- smpplib/gsm.py
`gsm_encode` works incorrectly in Python 2.x, e.g. `"Test"` converts to `"pΠ¿¿I"`. This is because of:
> https://pythonhosted.org/six/#six.u
> On Python 2, `u()` doesn’t know what the encoding of the literal is. Each byte is **converted directly to the unicode codepoint of the same value**. Because of this, **it’s only safe to use `u()` with strings of ASCII data**.
For example looking at `gsm` constant:
```python
In [13]: gsm.find('T')
Out[13]: 84
In [8]: gsm.find('T')
Out[8]: 112
```
The easiest way would be to import `unicode_literals` and/or use `u""` prefix but since you support 2.6 and <3.3 I decided to go with the simple `if`.
> gsm.py: Fix gsm_encode in Python 2.x

- smpplib/client.py
Inspecting the `receiver_mode` flag was deprecated in 80e4a4.
Remove initialization and toggling of this unused flag as cleanup.
> Client: do not initialize or set deprecated `receiver_mode`

- setup.py
Follow up to https://github.com/python-smpplib/python-smpplib/pull/70 because `encoding` is missing in Python 2.x.
> Follow up to PR #70, fix Python 2.x

- smpplib/consts.py
NOTIFICATION was misspelled as NOTIFICIATION. This change will break any clients already using this constant. Perhaps both variants should be available as constants?
> Fix typo of NOTIFICATION in consts - breaks client

- CHANGELOG.md
- smpplib/command.py
Explicit is better than implicit. If both fields are present, `short_message` is silently set to empty. This makes debugging more difficult.
> Raise an error if `message_payload` is used together with `short_message`

- smpplib/client.py
log aggregation tools(like sentry) use unformatted [msg](https://docs.python.org/3/library/logging.html#logrecord-attributes) to aggregate logs.
we can rely on python `logging` module to do `msg % attrs` in this case and we will have better representation of errors in sentry.
> fix: don't use % operator in logging

- smpplib/client.py
After playing and testing the lib, I noticed that under "stress" - sending around 10 SMS/s and receiving the DLRs on the same connection - I encountered failing PDUs out of nowhere.
I pinned the issue down to the fact that the current implementation expects all the data from a pdu to be in the buffer and sometimes, it isn't. WHen that's the case, it will retrieve less data than the expected length and it then messes all following PDUs (if it doesn't raise an exception before).
I first tried using the MSG_WAITALL flag but this didn't seem to work (surely something platform dependant) so I made that little loop which fixes everything on my side.
Let me know if I missed something, or if you need more information
> Wait for the full PDU before parsing

- smpplib/client.py
- smpplib/command.py
I'm not sure about the way I forced the message_state field to be mandatory in query_sm_resp (I really lost a lot of time trying to understand why my code wasn't working by the way) but otherwise this is working.
```python
smpp.query_message(
message_id='MESSAGEIDASSIGNEDBYSMSC',
source_addr_ton=smpplib.consts.SMPP_TON_INTL,
source_addr='SENDERPHONENUM',
)
```
> Add query_sm & query_sm_resp support

- smpplib/client.py
Also removed `logger.debug("Link Enquiry...")` because we already log:
```
DEBUG:smpplib.client:Read enquire_link PDU
DEBUG:smpplib.client:Sending enquire_link_resp PDU
```
> enquire_link_resp now echo original sequence

- smpplib/client.py
Привет! 
Возникла ошибка `NameError: name 'self' is not defined` при обращении к `staticmethod`'ам класса `Client` в случае, если функции `message_sent_handler`, `message_received_handler` не переопределены через сеттер.
```python
self.logger.warning('Message sent handler (Override me)')
NameError: name 'self' is not defined
WARNING:smpp.Client.139678295389576:<smpplib.client.Client object at 0x7f09632df588> was not closed
```
Более того, при возникновении ошибки не обрывается `TCP` соединение, что вызывает у шлюза определенные проблемы.
> Name self is not defined in Client

- smpplib/command.py
Fixed DataSM param naming error: alert_on_message_delivery
Fixed logic bug in int_tlv generation. "0" values were ignored due to bad None check.
Populated DataSMResp params for proper parsing.
> DataSM bugfixes

- smpplib/command.py
I noticed odd behavior when I specified a password with 9 characters (SMPP spec limit to 8 chars and NULL terminator). 
It seems like the max check was off by 1, and so it was passing a 9 byte password and 1 NULL for a total of 10 octets.
e.g with the following inputs:
password works
password1 fails with bind password error from downstream smsc (smppsim in this case).
password12 works (get truncated to 8 chars).
> The max check should include the NULL terminator.

- README.md
- smpplib/client.py
- smpplib/command.py
- tests/test_client.py
- tests/test_command.py
See page 43 of https://smpp.org/SMPP_v3_4_Issue1_2.pdf for details on why.
This adds a new flag `allow_unknown_opt_params` to the client which is passed down to the PDU parsing code to control if unknown optional parameters are allowed. The default behaviour is unchanged to avoid a breaking change, but the example code in the readme has been updated to use the new setting.
Fixes #111
> Fix not allowing unknown optional parameters

- smpplib/client.py
The socket timeout wasn't being set if the socket was created by the constructor (rather than the create method).
> Fix not always setting the socket timeout

- smpplib/gsm.py
See #182
The condition for splitting a text is based on `text` variable although it should be on `encoded_text` cause some characters from the extended table counts for two characters.
> Fixed split message detection

- smpplib/client.py
https://github.com/python-smpplib/python-smpplib/blob/4d74dc1edb4462136dff0f61dec79fe59c609609/smpplib/client.py#L259-L260
`raw_pdu` can never be "falsy" as it was already tested above:
https://github.com/python-smpplib/python-smpplib/blob/4d74dc1edb4462136dff0f61dec79fe59c609609/smpplib/client.py#L241-L242
So this if-condition is never satisfied and the socket recv error is silently passed. It could potentially corrupt further recvs.
> fix socket recv error being silently ignored

- smpplib/command.py
- smpplib/tests/test_command.py
fixes [#214](https://github.com/python-smpplib/python-smpplib/issues/214)
made need_sequence=True for the following commands:
- BindTransmitter
- BindReceiver
- BindTransceiver
- Unbind
- DeliverySM
- EnquireLink
> increment sequence of commands as spec (fixes #214)
